### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
Hi, I'm making updates for Open Collective. Either you or another core contributor signed this repository up for Open Collective. This pull request adds financial contributors from your Open Collective https://opencollective.com/color-picker ❤️

  What it does:
  - adds a badge to show the latest number of financial contributors
  - adds a banner displaying contributors to the project on GitHub
  - adds a banner displaying all individuals contributing financially on Open Collective
  - adds a section displaying all organizations contributing financially on Open Collective, with their logo and a link to their website

We have also added a `postinstall` script to let people know after `npm|yarn install` that you are welcoming donations. Feel free to remove it if you don't want it. [[More info](https://github.com/opencollective/opencollective-postinstall)]

P.S: As with any pull request, feel free to comment or suggest changes.

  Thank you for your great contribution to the Open Source community. You are awesome! 🙌
  And welcome to the Open Collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other Open Source sustainers!

### CODE REVIEW

**Comment by tovic** [comment]
Thanks. Just one thing that still makes me doubtful. How about my ethics for the people who contribute? I mean, if I get income from this project, then what about the fee for contributors?

I am into this:

> Is it even ethical to accept money for a project to which others have contributed? How could money be shared with contributors? How to fairly decide who gets how much?

> https://hackaday.com/2019/07/05/how-not-to-get-paid-for-open-source-work/

What do you think?

**Comment by evolross** [comment]
If this project is going Open Collective... I would love to see touchscreen device support.  For me, I have plans to swap this package out for a touchscreen-compatible package as soon as I get the chance.

**Comment by tovic** [comment]
This already has touch-screen support from the start.

**Comment by evolross** [comment]
Doh... confused this for another package... sorry about that. I stand corrected!

**Pull request merged**
